<?php

########################################################################
# Extension Manager/Repository config file for ext: "super_forms"
#
# Auto generated by Extension Builder 2012-02-08
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Super Forms',
	'description' => 'Creating forms the extbase way',
	'category' => 'plugin',
	'author' => 'Felix Oertel, Tobias Liebig',
	'author_email' => 'work@etobi.de, f@oer.tel',
	'author_company' => 'DevButze',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>